-- Displayed top 3 products total net revenue, where order status is 'Delivered'.

SELECT
	P.PRODUCT_NAME,
	ROUND(
		SUM(OI.UNIT_PRICE * OI.UNITS * (1 - OI.DISCOUNT)),
		2
	) AS TOTAL_NET_REVENUE
FROM
	ORDER_ITEMS OI
	JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
	JOIN ORDERS O ON OI.ORDER_ID = O.ORDER_ID
WHERE
	O.STATUS = 'Delivered'
GROUP BY
	P.PRODUCT_NAME
ORDER BY
	TOTAL_NET_REVENUE DESC
LIMIT
	3